# Generated by Django 4.1.3 on 2022-11-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_rename_name_universitycampus_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='title',
            new_name='name',
        ),
    ]
